services:
  postgres:
    image: postgres
    container_name: exchange_rates_db
    restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exchange_rates
    volumes:
      - exchange_rates_postgres_data:/var/lib/postgresql/data

  status-page:
    build:
      context: ./status-page
    container_name: status_page
    ports:
      - "8090:80"
    restart: always

  redis:
    image: redis/redis-stack:latest
    container_name: exchange_rates_redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  exchange_rates_postgres_data:
